### ISSUE TITLE
Second half of array should be used as well

### ISSUE THREAD

**Issue by vlsi** [PavelKatunin/AsciiSymbolsCounter#1]
Try testing on the following sequence: ababaccccc

**Comment by PavelKatunin** [comment]
@vlsi I've just updated tests for that case, "ababaccccc" and all works for me
https://github.com/PavelKatunin/AsciiSymbolsCounter/commit/23c8e60a37877815eb1301f95d803c2a37e7a343
Am I missing something?

**Comment by vlsi** [comment]
Never mind. I missed `mergeMappingArraysToFirst` call.
